export const GAME_MODES = [
  {
    id: "quick-date",
    name: "Quick Date",
    cardCount: 10,
    description: "A tight little jackpot fantasy with laughs, luxury, and a soft landing.",
    preferredCategories: [
      "The First 24 Hours",
      "Rich Energy",
      "Wild Spending",
      "Dream Home",
      "Travel Like It's a Movie",
      "People We Would Help",
      "The New Daily Life",
      "Our Future",
      "Secret Soft Spot"
    ],
    emotionalProgression: ["easy", "luxury", "personal", "future", "closing"],
    deck: [
      "first-swipe",
      "quiet-celebration",
      "millionaire-outfit",
      "petty-luxury",
      "view-from-bed",
      "private-jet-first",
      "secret-rescue",
      "perfect-tuesday",
      "yearly-tradition",
      "promise-after-win"
    ]
  },
  {
    id: "full-jackpot-night",
    name: "Full Jackpot Night",
    cardCount: 30,
    description: "A full evening arc from the first secret to the future you might build.",
    preferredCategories: [
      "The First 24 Hours",
      "Rich Energy",
      "Dream Home",
      "Travel Like It's a Movie",
      "People We Would Help",
      "The New Daily Life",
      "Wild Spending",
      "Our Future",
      "Secret Soft Spot",
      "Big Moves"
    ],
    emotionalProgression: ["easy", "visual", "funny", "personal", "generous", "future", "closing"],
    deck: [
      "first-message",
      "first-swipe",
      "quiet-celebration",
      "hotel-check-in",
      "driver-or-drive",
      "quiet-flex",
      "where-home",
      "one-room",
      "private-jet-first",
      "city-takeover",
      "ridiculous-collection",
      "because-we-can-party",
      "secret-rescue",
      "friend-upgrade",
      "anonymous-magic",
      "perfect-tuesday",
      "quit-or-keep",
      "new-hobby-era",
      "yearly-tradition",
      "our-place",
      "family-table",
      "childhood-luxury",
      "safe-place",
      "old-dream",
      "dream-business",
      "creative-project",
      "relocation-question",
      "build-together",
      "future-anniversary",
      "promise-after-win"
    ]
  },
  {
    id: "rich-ridiculous",
    name: "Rich & Ridiculous",
    cardCount: 15,
    description: "Luxury, comedy, dramatic entrances, and harmlessly absurd spending.",
    preferredCategories: ["Rich Energy", "Wild Spending", "Travel Like It's a Movie", "The First 24 Hours"],
    emotionalProgression: ["easy", "luxury", "chaos", "movie", "closing"],
    deck: [
      "first-lie",
      "first-breakfast",
      "millionaire-outfit",
      "hotel-check-in",
      "signature-service",
      "restaurant-takeover",
      "driver-or-drive",
      "ridiculous-collection",
      "because-we-can-party",
      "petty-luxury",
      "personal-theme-song",
      "buy-the-place",
      "dramatic-entrance",
      "million-euro-joke",
      "quiet-flex"
    ]
  },
  {
    id: "dream-life",
    name: "Dream Life",
    cardCount: 15,
    description: "Homes, travel, rituals, daily freedom, and the life you would actually love waking up in.",
    preferredCategories: [
      "Dream Home",
      "Travel Like It's a Movie",
      "The New Daily Life",
      "Our Future"
    ],
    emotionalProgression: ["easy", "visual", "daily", "shared", "closing"],
    deck: [
      "first-breakfast",
      "where-home",
      "view-from-bed",
      "kitchen-fantasy",
      "house-rule",
      "private-jet-first",
      "island-scene",
      "never-leaving",
      "perfect-tuesday",
      "calendar-cleanse",
      "slow-day",
      "new-identity",
      "yearly-tradition",
      "our-place",
      "future-anniversary"
    ]
  },
  {
    id: "soft-meaningful",
    name: "Soft & Meaningful",
    cardCount: 15,
    description: "Gentler cards about care, safety, generosity, nostalgia, and shared promises.",
    preferredCategories: ["People We Would Help", "Our Future", "Secret Soft Spot", "The New Daily Life"],
    emotionalProgression: ["easy", "care", "memory", "future", "closing"],
    deck: [
      "quiet-celebration",
      "secret-rescue",
      "family-surprise",
      "anonymous-magic",
      "parents-day-off",
      "stranger-story",
      "perfect-tuesday",
      "body-and-mind",
      "slow-day",
      "family-table",
      "protect-one-thing",
      "comfort-purchase",
      "old-dream",
      "peace-budget",
      "promise-after-win"
    ]
  }
];

export const MODE_BY_ID = Object.fromEntries(GAME_MODES.map((mode) => [mode.id, mode]));
